### ISSUE TITLE
Add link to github pages to repository info

### ISSUE THREAD

**Issue by mlocati** [concretecms/doctrine-xml#7]
What about updating the repository info by adding a link to the GitHub Pages page https://concretecms.github.io/doctrine-xml/ ?

I mean, we currently have:

![immagine](https://user-images.githubusercontent.com/928116/176542465-ae0736c9-5bcb-43f6-bffd-4ef635d43cc6.png)

I'd edit that info so that it results in

![immagine](https://user-images.githubusercontent.com/928116/176542527-a3908378-d8ce-4db3-bd13-50248eb9c025.png)

**Comment by aembler** [comment]
Done
